apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-website
  labels:
    app: ecommerce
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
        - name: ecommerce-container
          image: your-ecommerce-image:latest  # Replace with your image
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              value: "mysql://user:password@mysql-service:3306/ecommerce"
            - name: API_KEY
              value: "your_api_key"  # Replace with actual API key
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000  # You can specify a port or let Kubernetes choose
  selector:
    app: ecommerce
